[client]
port   =  %MYSQL_PORT%
socket = "%SERVICE_PATH%mysql/mysql.sock"

[mysqld]
server-id = 1
port      = %MYSQL_PORT%
socket    = "%SERVICE_PATH%mysql/mysql.sock"
basedir   = "%SERVICE_PATH%mysql"
tmpdir    = "%ROOT_PATH%tmp/mysql"
datadir   = "%SERVICE_PATH%mysql/data"
pid_file  = "%SERVICE_PATH%mysql/mysql.pid"

secure_file_priv = "%ROOT_PATH%tmp/NULL"

bind-address            = 127.0.0.1
max_allowed_packet      = 20M
table_cache             = 64

max_connections = 600
innodb_buffer_pool_size = 512M
innodb_file_per_table   = 1
innodb_log_files_in_group = 2
innodb_log_file_size    = 256M
innodb_log_buffer_size  = 16M
key_buffer_size         = 16M
sort_buffer_size        = 2M
join_buffer_size        = 2M
query_cache_size        = 40M
query_cache_limit       = 2M
bulk_insert_buffer_size = 64M
read_buffer_size        = 2M
read_rnd_buffer_size    = 16M
thread_cache_size       = 300

net_buffer_length       = 8K
myisam_sort_buffer_size = 8M

default-storage-engine=InnoDB

log_error = "%LOG_PATH%mysql/mysql_error"

[mysqldump]
quick
max_allowed_packet = 16M

[mysql]
no-auto-rehash

[isamchk]
key_buffer_size  = 20M
sort_buffer_size = 20M
read_buffer      = 2M
write_buffer     = 2M

[myisamchk]
key_buffer_size  = 20M
sort_buffer_size = 20M
read_buffer      = 2M
write_buffer     = 2M

[mysqlhotcopy]
interactive-timeout
